name: NPM Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Setting up NodeJS and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Installing PNPM
        run: npm install -g pnpm

      - name: Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: Building react-ui
        run: pnpm run build --filter react-ui

      - name: Publishing react-ui
        run: npm publish --access=public
        working-directory: ./packages/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Building preact-ui
        run: pnpm run build --filter preact-ui

      - name: Publishing preact-ui
        run: npm publish --access=public
        working-directory: ./packages/preact
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
